version: '3'

services:

  scpr:
    build: .
    container_name: scpr
    ports:
      - 3000:3000/tcp
    networks:
      scpr-network:
        aliases:
          - scpr
    command: ./docker-startup.sh
    environment:
      SCPRV4_ELASTICSEARCH_HOST: elasticsearch:9200
      SCPRV4_RESQUE_HOST: redis://redis:6379
      SCPRV4_MYSQL_HOST: mysql
    volumes:
      - ./:/home/scpr
      - scpr-bundle:/usr/local/bundle
      - scpr-gems:/usr/local/lib/ruby/gems/

  mysql:
    image: scpr/restore-percona-backup
    container_name: scpr-mysql
    ports:
      - 3200:3200/tcp
      - 3306:3306/tcp
    restart: always
    command: $SCPRV4_DEPLOYBOT_TOKEN
    environment:
      MYSQL_ROOT_PASSWORD: password
      SCPRV4_DEPLOYBOT_TOKEN: ${SCPRV4_DEPLOYBOT_TOKEN}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      scpr-network:
        aliases:
         - mysql

  redis:
    image: redis:4.0.1-alpine
    command: redis-server
    container_name: scpr-redis
    restart: always
    ports:
      - 6379:6379/tcp
    networks:
      scpr-network:
        aliases:
         - redis

  memcached:
    image: memcached:1.5.0-alpine
    command: memcached
    container_name: scpr-memcached
    restart: always
    ports:
      - 11211:11211
    networks:
      scpr-network:
        aliases:
          - memcached

  elasticsearch:
    image: elasticsearch:1.7-alpine
    container_name: scpr-elasticsearch
    restart: always
    ports:
      - 9200:9200/tcp
      - 9300:9300/tcp
      - 9250:9250/tcp
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch
    networks:
      scpr-network:
        aliases:
         - elasticsearch

volumes:
  scpr-bundle:
  scpr-gems:
  mysql-data:
  elasticsearch-data:

networks:
  scpr-network:

