development:
  adapter: mysql2
  reconnect: true
  database: scpr
  host: <%= ENV['SCPRV4_DEVELOPMENT_DATABASE_IP'] %>
  port: 3306
  username: root
test:
  adapter: mysql2
  reconnect: true
  database: scprv4_test
